#Cap 3 configuracion config server
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/smgomez92/configuracion/
          username: smgomez92
          password: Santy_172167
