#Cap 3 configuracion config server
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/smgomez92/Programacion-Distribuida-Practicas/
          username: santy.rosca@hotmail.com
          password: Santy_172167
